In [60]:
import pandas as pd
import numpy as np
import os
path=r'C:\Users\fanyu\Downloads\MachineLearningCVE\MachineLearningCVE'

dos_file1=path +'//'+'Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv'
dos_file2=path+'//'+'Friday-WorkingHours-Morning-bot.pcap_ISCX.csv'
dos_file3=path +'//'+'Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv'
dos_file4=path+'//'+'Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv'
dos_file5=path+'//'+'Tuesday-WorkingHours-Brute-Force.pcap_ISCX.csv'

patho='C://Users//fanyu//Desktop//dpdk//os'

path=patho+'//'+'ospcap_Flow.csv'
patho='C://Users//fanyu//Desktop//dpdk//syn'
path2=patho+'//'+'synpcap_Flow.csv'
path27=patho+'//'+'syn27pcap_Flow.csv'

tar_cic1=pd.read_csv(path,encoding='ISO-8859-1')
tar_cic2=pd.read_csv(path2,encoding='ISO-8859-1')
tar=pd.concat([tar_cic1,tar_cic2])
#dos_test=pd.read_csv(path, encoding='ISO-8859-1')
target=tar.drop(tar.columns[[0,1,2,3,5,6]],axis=1,inplace=False)

dos_test27=pd.read_csv(path27, encoding='ISO-8859-1')
dos_test=pd.concat([tar_cic1,dos_test27])
target27=dos_test.drop(dos_test.columns[[0,1,2,3,5,6]],axis=1,inplace=False)

dos_cic1=pd.read_csv(dos_file1)
dos_cic2=pd.read_csv(dos_file2)
dos_cic3=pd.read_csv(dos_file3)
dos_cic4=pd.read_csv(dos_file4)
dos_cic5=pd.read_csv(dos_file5)
dos_cic=pd.concat([dos_cic1,dos_cic2,dos_cic3,dos_cic4,dos_cic5])
source=dos_cic.drop(' Fwd Header Length.1',axis=1)

pd.set_option('display.max_columns',None)

In [65]:
tar_cic1.shape

(65671, 84)

In [66]:
#from sklearn import preprocessing
#from sklearn.preprocessing import OneHotEncoder
#from sklearn import cross_validation

source_x=source.iloc[:,:77]
source_y=source.iloc[:,77]
target_x=target.iloc[:,:77]
target_y=target.iloc[:,77]
target27_x=target27.iloc[:,:77]
target27_y=target27.iloc[:,77]


In [31]:
#from sklearn import preprocessing
from sklearn import preprocessing
from sklearn import cross_validation
source_xtrain,source_xtest,source_ytrain,source_ytest=cross_validation.train_test_split(source_x,source_y,test_size=0.4)
#source_xtrain=source_xtrain.fillna(method='backfill')
    
#source_xtrain=source_xtest.fillna(method='backfill')

xtrain2=pd.DataFrame(source_xtrain,dtype=np.float)
c=xtrain2.drop(columns='Flow Bytes/s', axis= 1)
b=c.drop(columns=' Flow Packets/s', axis= 1)
xtrain3=preprocessing.StandardScaler().fit_transform(b)
    
xtest2=pd.DataFrame(source_xtest,dtype=np.float)
m=xtest2.drop(columns='Flow Bytes/s', axis= 1)
n=m.drop(columns=' Flow Packets/s', axis= 1)
xtest3=preprocessing.StandardScaler().fit_transform(n)


source_x_train = xtrain3.reshape((xtrain3.shape[0],xtrain3.shape[1],1))
source_x_test =xtest3.reshape((xtest3.shape[0],xtest3.shape[1],1))
#source_y_train=ytrain2
#source_y_test=ytest2


In [36]:
ytrain2

array([0, 0, 0, ..., 0, 0, 0], dtype=object)

In [34]:
ytrain2=source_ytrain.values
ytest2=source_ytest.values

for j in range(len(ytrain2)):
    if ytrain2[j]== 'BENIGN':
        ytrain2[j]=0
    if ytrain2[j]== 'DDoS':
        ytrain2[j]=1
    if ytrain2[j]== 'Bot':
        ytrain2[j]=2
    if ytrain2[j]== 'PortScan':
        ytrain2[j]=3
    if ytrain2[j]== 'Web Attack':
        ytrain2[j]=4
    if ytrain2[j]=='FTP-Patator' or ytrain2[j]=='SSH-Patator':
        ytrain2[j]=5
for j in range(len(ytest2)):
    if ytest2[j]== 'BENIGN':
        ytest2[j]=0
    if ytest2[j]== 'DDoS':
        ytest2[j]=1
    if ytest2[j]== 'Bot':
        ytest2[j]=2
    if ytest2[j]== 'PortScan':
        ytest2[j]=3
    if ytest2[j]== 'Web Attack':
        ytest2[j]=4
    if ytest2[j]== 'FTP-Patator' or ytest2[j]=='SSH-Patator':
        ytest2[j]=5



In [35]:
ytest2

array([0, 0, 0, ..., 0, 0, 0], dtype=object)

In [37]:
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoded_Y = encoder.fit_transform(ytrain2)
# convert integers to dummy variables (one hot encoding)
ytrain3 = np_utils.to_categorical(encoded_Y)
source_y_train=ytrain3

encoder = LabelEncoder()
encoded_Y = encoder.fit_transform(ytest2)
# convert integers to dummy variables (one hot encoding)
ytest3 = np_utils.to_categorical(encoded_Y)
source_y_test=ytest3

Using TensorFlow backend.


In [ ]:
ytrain2.shape

In [8]:
ind=0
ind_list=[]
for s in source_y_train:
    if s[0]==1:
        ind_list.append(ind)
    ind+=1
len(ind_list)
#len(source_y_train)

348956

In [67]:
#def process():              

#target_xtrain,target_xtest,target_ytrain,target_ytest=cross_validation.train_test_split(target_x,target_y,test_size=0.01)
target_xtrain,target_ytrain=target_x,target_y
target_xtest,target_ytest=target27_x,target27_y
#target_xtrain=target_xtrain.fillna(method='backfill')
    
#target_xtrain=target_xtest.fillna(method='backfill')

xtrain2=pd.DataFrame(target_xtrain,dtype=np.float)
c=xtrain2.drop(columns='Flow Bytes/s', axis= 1)
b=c.drop(columns='Flow Packets/s', axis= 1)
xtrain3=preprocessing.StandardScaler().fit_transform(b)
    
xtest2=pd.DataFrame(target_xtest,dtype=np.float)
m=xtest2.drop(columns='Flow Bytes/s', axis= 1)
n=m.drop(columns='Flow Packets/s', axis= 1)
xtest3=preprocessing.StandardScaler().fit_transform(n)

ytrain2=target_ytrain.values
ytest2=target_ytest.values
for j in range(len(ytrain2)):
    if ytrain2[j][0]== 'N':
        ytrain2[j]=0
    else:
        ytrain2[j]=1
#for j in range(len(ytest2)):
    #if ytest2[j][0]== 'N':
        #ytest2[j]=0
    #else:
       # ytest2[j]=1

target_x_train = xtrain3.reshape((xtrain3.shape[0],xtrain3.shape[1],1))
target_x_test =xtest3.reshape((xtest3.shape[0],xtest3.shape[1],1))

#X_train = np.reshape(trainX, (trainX.shape[0],trainX.shape[1],1))
#X_test = np.reshape(testT, (testT.shape[0],testT.shape[1],1))

target_y_train=ytrain2
#target_y_test=ytest2


In [44]:
import keras
from keras.models import Sequential, Model
from keras import layers
from keras.optimizers import SGD
length = 75

input_layerA = layers.Input(name='input', shape=(length ,1))

x = layers.Conv1D(64, 3,padding='same', name='conv_1', kernel_regularizer = 'l2')(input_layerA)
x = layers.MaxPooling1D(2)(x)
#x = layers.LeakyReLU(name='leaky_1')(x)

#x = layers.Conv1D(64, 3,padding='same', name='conv_2', kernel_regularizer = 'l2')(x)
#x = layers.MaxPooling1D(2)(x)
#x = layers.LeakyReLU(name='leaky_2')(x)           

x = layers.Conv1D(128, 3,padding='same', name='conv_3', kernel_regularizer = 'l2')(x)
feature = layers.MaxPooling1D(2)(x)


y = layers.Flatten()(feature)
y  = layers.Dense(128, activation="relu")(y)
bottle1 = layers.Dense(64, activation="relu")(y)
#y = layers.Dropout(0.5)(y)
final_classifier  = layers.Dense(6, activation="sigmoid")(bottle1)
source_cnn = Model(inputs=input_layerA, outputs=final_classifier)

#cnn.summary()

source_feature=Model(inputs=input_layerA,outputs=bottle1)

In [47]:
import keras.backend as K
from keras import layers,losses
from keras.engine.topology import Layer
source_cnn.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

source_cnn.fit(source_x_train[:100000,:],source_y_train[:100000,:],epochs=1,validation_data=(source_x_test[:10000,:],source_y_test[:10000,:]))

Train on 100000 samples, validate on 10000 samples
Epoch 1/1
100000/100000 [==============================] - 27s 266us/step - loss: 0.0667 - accuracy: 0.9850 - val_loss: 0.0577 - val_accuracy: 0.9859


In [40]:

from keras.models import load_model
import keras.backend as K
from keras import layers,losses
from keras.engine.topology import Layer
#source_cnn=load_model(r'H:\model\C5_source_cnn.h5')

In [48]:
length = 75

input_layerB = layers.Input(name='input', shape=(length ,1))

x = layers.Conv1D(64, 3,padding='same', name='conv_1', kernel_regularizer = 'l2')(input_layerB)
x = layers.MaxPooling1D(2)(x)
#x = layers.LeakyReLU(name='leaky_1')(x)

#x = layers.Conv1D(64, 3,padding='same', name='conv_2', kernel_regularizer = 'l2')(x)
#x = layers.MaxPooling1D(2)(x)
#x = layers.LeakyReLU(name='leaky_2')(x)           

x = layers.Conv1D(128, 3,padding='same', name='conv_3', kernel_regularizer = 'l2')(x)
feature = layers.MaxPooling1D(2)(x)


y = layers.Flatten()(feature)
y  = layers.Dense(128, activation="relu")(y)
bottle2 = layers.Dense(64, activation="relu")(y)
#y = layers.Dropout(0.5)(y)
final_classifier2  = layers.Dense(6, activation="sigmoid")(bottle2)
target_cnn = Model(inputs=input_layerB, outputs=final_classifier2)

target_feature=Model(inputs=input_layerB,outputs=bottle2)

In [49]:
sw=source_cnn.get_weights()
target_cnn.set_weights(sw)

In [50]:
##discriminator
length=64
input_layerC = layers.Input(name='input', shape=(length, ))

# Encoder
#x = layers.Dense(10, activation='relu')(input_layerC)
#x = layers.Dense(10, activation='relu')(x)
#d = layers.Dense(1, activation='relu')(x)
d = layers.Dense(1, activation='sigmoid')(input_layerC)


discriminator1 = Model(inputs=input_layerC, outputs=d)


In [51]:
length=64
input_layerD = layers.Input(name='input', shape=(length, ))

# Encoder
#x = layers.Dense(50, activation='relu')(input_layerD)
x = layers.Dense(40, activation='relu')(input_layerD)
x = layers.Dense(10, activation='relu')(x)
#d = layers.Dense(1, activation='relu')(x)
d = layers.Dense(1, activation='sigmoid')(x)


discriminator2 = Model(inputs=input_layerD, outputs=d)


In [52]:
import keras.backend as K
from keras import layers,losses
from keras.engine.topology import Layer


length=75


s_origin = layers.Input(name='input3', shape=(length ,1))
t_origin = layers.Input(name='input4', shape=(length ,1))

cgan_input = t_origin
#sf=source_feature(cgan_input[0])
tf=target_feature(cgan_input)
generator_output=tf
cgan_output = discriminator2(generator_output)
cgan = Model(cgan_input,cgan_output)
cgan.compile(optimizer='adam',loss=['binary_crossentropy'])
discriminator1.compile(optimizer='adam',loss=['binary_crossentropy'])
discriminator2.compile(optimizer='adam',loss=['binary_crossentropy'])
target_fe_trainer=cgan



def closs(yt,yp):
    #print(yp)
    #print(yt)
    #res=losses.binary_crossentropy(yt,yp)
    #return -K.sum(yt * K.log(yp + 1e-7)) -K.sum((1-yt)*K.log(1-yp+ 1e-7))
    loss = -yt*K.log(yp+0.000001)-(1-yt)*K.log((1-yp+0.000001))
    return loss
    #return K.abs(yt-yp)

#yt*log(yp)+(1-yt)*log(1-yp)


In [53]:
def get_data_generator(data, batch_size=32):
    datalen = len(data)
    cnt = 0
    while True:
        idxes = np.arange(datalen)
        #np.random.shuffle(idxes)
        cnt += 1
        for i in range(int(np.ceil(datalen/batch_size))):
            train_x = np.take(data, idxes[i*batch_size: (i+1) * batch_size], axis=0)
            y = np.ones(len(train_x))
            yield train_x
source_train_data_generator=get_data_generator(source_x_train)
target_train_data_generator=get_data_generator(target_x_train)

In [54]:
niter=300

for i in range(niter):
    ################
    
    source_x_train_batch = source_train_data_generator.__next__()
    target_x_train_batch=target_train_data_generator.__next__()
    
    source_cnn.trainable=False
    target_cnn.trainable=False
    
    discriminator1.trainable=True
    discriminator2.trainable=True
    
    sf=source_feature.predict(source_x_train_batch)
    tf=target_feature.predict(target_x_train_batch)
    
    sf_tf=np.concatenate([sf,tf],axis=0)
    #sb_tb=np.concatenate([source_x_train_batch,target_x_train_batch],axis=0)
    label1=np.concatenate([np.ones(len(sf)),np.zeros(len(tf))],axis=0)
    loss1=discriminator1.train_on_batch(sf_tf,label1)
    
    ws=1.0/(discriminator1.predict(sf)+1.0)
    #ws=discriminator1.predict(sf)
    
    ws_sf_tf=np.concatenate([sf*ws,tf],axis=0)
    label2=np.concatenate([np.ones(len(sf)),np.zeros(len(tf))],axis=0)
    loss2=discriminator2.train_on_batch(ws_sf_tf,label2)
    
    
    #########################
    discriminator1.trainable=False
    discriminator2.trainable=False
    target_feature.trainable=True
    source_cnn.trainable=False
    
    
    loss_fe=target_fe_trainer.train_on_batch(target_x_train_batch,np.ones(len(tf)))
    if i % 25 == 0:
        print(f'niter: {i+1}, fe_loss: {loss_fe}, d_loss:{loss1},{loss2}')

D:\Anaconda3.6\lib\site-packages\keras\engine\training.py:297: UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
  'Discrepancy between trainable weights and collected trainable'


niter: 1, fe_loss: 7.489351272583008, d_loss:0.5966987609863281,0.5476371049880981


D:\Anaconda3.6\lib\site-packages\keras\engine\training.py:297: UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
  'Discrepancy between trainable weights and collected trainable'


niter: 26, fe_loss: 0.08351488411426544, d_loss:1.2198371887207031,2.217899799346924


KeyboardInterrupt: 

In [68]:
xx=target_cnn.predict(target_x_test)

In [87]:
y_pred=[]
for x in xx:
    a=x.tolist().index(max(x[1:6]))
    y_pred.append(a)
#print(y_pred)

In [84]:
syn=[21,37,62,68,78,83,100,114,145,163,176,180,195,209,227,241,
245,260,273,307,312,314,329,344,371,391,485,491,495]
os=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,81,82,83,84,85,86,87,88,89,594,11331,14596,15255,31756,46563,55502,56721]
#for i in range(len(syn)):
   # syn[i]=syn[i]+66168
#print(syn)


ind=0
y_true=[]
for s in range(65671):
    if s not in os:
        y_true.append(3)
    else:
        y_true.append(0)

for s in range(497):
    if s not in syn:
        y_true.append(1)
    else:
        y_true.append(0)
#print(y_true)

In [100]:
y_pred.index(4)

11331

In [96]:
from sklearn.metrics import confusion_matrix
C=confusion_matrix(y_true, y_pred)
C
acc=(C[0,0]+C[1,1]+C[2,2]+C[3,3]+C[4,4])/C.sum()
acc,C,C.sum()

(0.8677306250755652, array([[   52,    72,     0,     1,     1],
        [    1,   456,     0,    11,     0],
        [    0,     0,     0,     0,     0],
        [    0,  7369,  1297, 56908,     0],
        [    0,     0,     0,     0,     0]], dtype=int64), 66168)

In [101]:
cnf_matrix = confusion_matrix(y_true, y_pred)
print(cnf_matrix)
#[[1 1 3]
# [3 2 2]
# [1 3 1]]

FP = cnf_matrix.sum(axis=0) - np.diag(cnf_matrix)  
FN = cnf_matrix.sum(axis=1) - np.diag(cnf_matrix)
TP = np.diag(cnf_matrix)
TN = cnf_matrix.sum() - (FP + FN + TP)

FP = FP.astype(float)
FN = FN.astype(float)
TP = TP.astype(float)
TN = TN.astype(float)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)
# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print(ACC,TPR,FPR)
x=(1.51418794e-05+1.13257230e-01+2.02020202e-02)/3
print(x)

[[   52    72     0     1     1]
 [    1   456     0    11     0]
 [    0     0     0     0     0]
 [    0  7369  1297 56908     0]
 [    0     0     0     0     0]]
[0.99886652 0.88736247 0.98039838 0.86884899 0.99998489] [0.41269841 0.97435897        nan 0.86784396        nan] [1.51418794e-05 1.13257230e-01 1.96016201e-02 2.02020202e-02
 1.51130456e-05]
0.044491464026466664


D:\Anaconda3.6\lib\site-packages\ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in true_divide
D:\Anaconda3.6\lib\site-packages\ipykernel_launcher.py:28: RuntimeWarning: invalid value encountered in true_divide


In [72]:
a=discriminator1.predict(source_feature.predict(source_x_test))
#b=discriminator1.predict(target_feature.predict(target_x_train))

In [129]:
aal=[]
for aa in range(len(a)):
    print(a[aa])
    if a[aa]<0.5:
        
        aal.append(aa)

[0.52419055]
[0.548801]
[0.4653111]
[0.5634822]
[0.54302543]
[0.49153927]
[0.47238728]
[0.55278075]
[0.538834]
[0.53877544]
[0.50389415]
[0.5469264]
[0.5310989]
[0.53873736]
[0.54381925]
[0.50089973]
[0.5357096]
[0.5359273]
[0.5482791]
[0.5322036]
[0.53543717]
[0.53049475]
[0.54660875]
[0.5464171]
[0.5241651]
[0.5355567]
[0.5569634]
[0.54120344]
[0.52626276]
[0.5474326]
[0.531674]
[0.5523634]
[0.5398479]
[0.5042926]
[0.55837214]
[0.56115806]
[0.5354391]
[0.48323524]
[0.5456151]
[0.54105246]
[0.43775883]
[0.53354603]
[0.49102584]
[0.46244937]
[0.53612375]
[0.5590426]
[0.5475066]
[0.5239367]
[0.49181637]
[0.53141564]
[0.5318268]
[0.5021977]
[0.5491319]
[0.5559364]
[0.52834]
[0.52428466]
[0.52383107]
[0.5226992]
[0.5255537]
[0.54863596]
[0.5395667]
[0.54272485]
[0.5549551]
[0.5596318]
[0.5451403]
[0.549809]
[0.4257123]
[0.54704845]
[0.53557897]
[0.5477598]
[0.5455625]
[0.54581636]
[0.450416]
[0.536144]
[0.5487067]
[0.53184164]
[0.53909075]
[0.5354433]
[0.5081863]
[0.53928447]
[0.54400074]

[0.54163903]
[0.5007598]
[0.46929014]
[0.5378741]
[0.5387167]
[0.50819486]
[0.53108746]
[0.5361683]
[0.5406413]
[0.48957327]
[0.44429964]
[0.53513867]
[0.5320019]
[0.53184175]
[0.54874676]
[0.55294055]
[0.5055729]
[0.5372647]
[0.54730153]
[0.54566216]
[0.53609407]
[0.38814574]
[0.54803914]
[0.48838192]
[0.5432384]
[0.4669019]
[0.5398775]
[0.5044201]
[0.53180915]
[0.53284776]
[0.5512341]
[0.5479123]
[0.4812543]
[0.5318935]
[0.5318098]
[0.5422]
[0.54902637]
[0.55436987]
[0.55778724]
[0.50287634]
[0.5439336]
[0.45885473]
[0.5364633]
[0.5464577]
[0.5470579]
[0.52437854]
[0.5530801]
[0.5319544]
[0.5563435]
[0.53076977]
[0.43828627]
[0.5367115]
[0.5064906]
[0.5560021]
[0.53559595]
[0.5250027]
[0.5457423]
[0.53117514]
[0.50981516]
[0.52891433]
[0.53113323]
[0.5318074]
[0.540039]
[0.49773636]
[0.52529347]
[0.50344867]
[0.4824364]
[0.49895617]
[0.51410943]
[0.53191286]
[0.5312009]
[0.54168826]
[0.5306337]
[0.4378213]
[0.52794313]
[0.48211643]
[0.535891]
[0.52981645]
[0.5362317]
[0.43423194]
[0.

[0.5474143]
[0.5600478]
[0.5355815]
[0.5354984]
[0.55019206]
[0.52268964]
[0.5569946]
[0.5241705]
[0.5357894]
[0.53108454]
[0.5508486]
[0.5319861]
[0.53692687]
[0.5241956]
[0.5469805]
[0.5318919]
[0.5422651]
[0.5472961]
[0.50960326]
[0.5360185]
[0.5390301]
[0.5122128]
[0.5315]
[0.5483812]
[0.5578863]
[0.5360622]
[0.4689847]
[0.53350884]
[0.5123804]
[0.5213502]
[0.53201723]
[0.45910516]
[0.5448325]
[0.47572815]
[0.5360278]
[0.5319939]
[0.53342426]
[0.54511935]
[0.5396541]
[0.53187513]
[0.5514795]
[0.531956]
[0.5586925]
[0.52439207]
[0.5409472]
[0.53357744]
[0.5409785]
[0.5540948]
[0.5408328]
[0.5474279]
[0.5299091]
[0.49745986]
[0.46172395]
[0.55247563]
[0.5041992]
[0.4737368]
[0.5456321]
[0.53897107]
[0.5436623]
[0.54888165]
[0.5041579]
[0.54197145]
[0.5379985]
[0.541459]
[0.5450498]
[0.45118526]
[0.5404884]
[0.49937814]
[0.5288036]
[0.5600769]
[0.5362039]
[0.5346062]
[0.50983065]
[0.4007102]
[0.53181994]
[0.5332532]
[0.46256393]
[0.47085163]
[0.55077165]
[0.546644]
[0.54260844]
[0.535

[0.53509545]
[0.5310614]
[0.5362877]
[0.48797578]
[0.45341936]
[0.5469257]
[0.49170476]
[0.5366745]
[0.53185815]
[0.55033356]
[0.5386176]
[0.5266627]
[0.5534894]
[0.5312209]
[0.5496651]
[0.52912134]
[0.54319656]
[0.53561896]
[0.54922163]
[0.5316846]
[0.5311976]
[0.5474254]
[0.55461746]
[0.51116884]
[0.547317]
[0.39958635]
[0.5472611]
[0.55288166]
[0.52493167]
[0.5607808]
[0.45715612]
[0.43293914]
[0.59354347]
[0.54717004]
[0.54826134]
[0.55483806]
[0.5301935]
[0.5353168]
[0.5317324]
[0.551567]
[0.5433244]
[0.5567744]
[0.53706175]
[0.53635895]
[0.47831085]
[0.53626615]
[0.5363193]
[0.5007087]
[0.53131026]
[0.54631805]
[0.5624705]
[0.52465445]
[0.50672096]
[0.5373525]
[0.5318528]
[0.49852693]
[0.554639]
[0.5416854]
[0.46123737]
[0.5038879]
[0.45715022]
[0.53581834]
[0.5408056]
[0.46238312]
[0.54229844]
[0.43833765]
[0.54642606]
[0.5318555]
[0.4869703]
[0.5263723]
[0.5635036]
[0.5308057]
[0.5380391]
[0.5475431]
[0.5309456]
[0.553224]
[0.5361255]
[0.5262766]
[0.53499085]
[0.53552085]
[0.51

[0.5478144]
[0.5513671]
[0.54689795]
[0.5310526]
[0.4818517]
[0.5138524]
[0.5353081]
[0.5456716]
[0.5292896]
[0.56104916]
[0.48316154]
[0.53638566]
[0.5050318]
[0.5469007]
[0.5617628]
[0.52841884]
[0.55319023]
[0.51114196]
[0.55495685]
[0.5458002]
[0.5292993]
[0.5469768]
[0.5437827]
[0.52415586]
[0.53160787]
[0.5442069]
[0.4498194]
[0.5310859]
[0.54434717]
[0.45717216]
[0.4819458]
[0.5464168]
[0.5467506]
[0.5415662]
[0.53726697]
[0.51454467]
[0.54945034]
[0.5517742]
[0.5529138]
[0.54327655]
[0.5149502]
[0.5423866]
[0.5261864]
[0.5184741]
[0.43140978]
[0.5361556]
[0.5499491]
[0.5319479]
[0.54043776]
[0.53538084]
[0.5305648]
[0.46924478]
[0.54034835]
[0.542545]
[0.5319376]
[0.5597404]
[0.5354747]
[0.5108314]
[0.56791335]
[0.4922817]
[0.5430553]
[0.542924]
[0.53899646]
[0.5366668]
[0.540073]
[0.53118664]
[0.46929014]
[0.5506592]
[0.5067938]
[0.5360241]
[0.53709334]
[0.5263664]
[0.54437435]
[0.5121799]
[0.53943855]
[0.5353973]
[0.48839727]
[0.53182197]
[0.44554877]
[0.5087511]
[0.5002359]


[0.53549683]
[0.4185705]
[0.54989964]
[0.5476691]
[0.5355262]
[0.539185]
[0.53641796]
[0.47882554]
[0.54551905]
[0.5286916]
[0.3996504]
[0.5642923]
[0.5241583]
[0.54062563]
[0.49229094]
[0.5414702]
[0.5489156]
[0.54413074]
[0.51061267]
[0.523927]
[0.548287]
[0.50794846]
[0.53914243]
[0.54562587]
[0.5393705]
[0.5385352]
[0.54675806]
[0.54991704]
[0.54952013]
[0.5298051]
[0.5107926]
[0.52706665]
[0.53184366]
[0.46355283]
[0.54053843]
[0.5490034]
[0.5354321]
[0.45341069]
[0.5401495]
[0.5354542]
[0.5491833]
[0.53182644]
[0.53251755]
[0.53194463]
[0.5319192]
[0.5485615]
[0.5496047]
[0.53149503]
[0.5546042]
[0.5457762]
[0.5331527]
[0.53606665]
[0.5501714]
[0.5296816]
[0.54065865]
[0.49061128]
[0.5444751]
[0.49894407]
[0.43671283]
[0.5243401]
[0.5054565]
[0.54792863]
[0.5404165]
[0.53092486]
[0.53285366]
[0.5403595]
[0.525679]
[0.54109687]
[0.54094124]
[0.5122937]
[0.5569991]
[0.55600935]
[0.53608125]
[0.5358731]
[0.54497355]
[0.5487887]
[0.5300691]
[0.52276605]
[0.5319181]
[0.54254323]
[0.53

[0.5305211]
[0.5353217]
[0.536005]
[0.46596134]
[0.52921593]
[0.52927876]
[0.5328271]
[0.5249218]
[0.53559846]
[0.4145367]
[0.5311966]
[0.5380361]
[0.5110131]
[0.53829306]
[0.53548753]
[0.46228755]
[0.5317995]
[0.5013715]
[0.5320151]
[0.4991255]
[0.50752234]
[0.5315257]
[0.5575961]
[0.55105734]
[0.48683923]
[0.459636]
[0.5462331]
[0.47977018]
[0.5353301]
[0.5365323]
[0.49735805]
[0.54597634]
[0.533133]
[0.53114766]
[0.53122956]
[0.5399574]
[0.55685335]
[0.45724282]
[0.5490038]
[0.56077075]
[0.53227437]
[0.5559886]
[0.52420086]
[0.53275865]
[0.5369626]
[0.4260429]
[0.4506984]
[0.50850075]
[0.5529549]
[0.53316116]
[0.5157077]
[0.546614]
[0.54284936]
[0.5367161]
[0.53188217]
[0.5513097]
[0.52446115]
[0.47043136]
[0.53150314]
[0.5495207]
[0.5005753]
[0.501822]
[0.5365349]
[0.5458165]
[0.54352474]
[0.54403913]
[0.5504365]
[0.5360753]
[0.5319508]
[0.53660256]
[0.53124493]
[0.5362568]
[0.46277988]
[0.53629565]
[0.5126682]
[0.5242099]
[0.53560597]
[0.54477155]
[0.5407928]
[0.5093084]
[0.462403

[0.50237864]
[0.5046127]
[0.5632838]
[0.54583263]
[0.5621249]
[0.49525958]
[0.5310502]
[0.54410934]
[0.51034236]
[0.52727354]
[0.5421297]
[0.5309488]
[0.52349466]
[0.540851]
[0.543934]
[0.5348513]
[0.51484287]
[0.5544987]
[0.52614933]
[0.55316144]
[0.46258208]
[0.53651065]
[0.54672664]
[0.49803543]
[0.4211386]
[0.5425906]
[0.501385]
[0.5481275]
[0.55144024]
[0.49995947]
[0.5368131]
[0.45661682]
[0.5310425]
[0.45892945]
[0.5493901]
[0.5415714]
[0.55274105]
[0.53247625]
[0.5361335]
[0.554]
[0.41485274]
[0.5382892]
[0.5143758]
[0.4918689]
[0.5514489]
[0.55306554]
[0.4701517]
[0.5354139]
[0.5454848]
[0.53747666]
[0.52546936]
[0.55952954]
[0.5335562]
[0.53594697]
[0.5449029]
[0.54638964]
[0.5361415]
[0.5474144]
[0.5461711]
[0.53186417]
[0.49916133]
[0.543137]
[0.45977366]
[0.5356423]
[0.53493214]
[0.5396603]
[0.54144675]
[0.54068327]
[0.5483586]
[0.5512965]
[0.52990216]
[0.43688664]
[0.53332686]
[0.55062515]
[0.5360245]
[0.5244199]
[0.531889]
[0.48178774]
[0.54203856]
[0.53936064]
[0.544258

[0.44756195]
[0.48281193]
[0.5314965]
[0.53938174]
[0.5392051]
[0.5433797]
[0.54259425]
[0.54973537]
[0.44129118]
[0.5482276]
[0.40313944]
[0.5309585]
[0.54084766]
[0.5178239]
[0.53109837]
[0.542503]
[0.53669524]
[0.52181786]
[0.52333087]
[0.5361482]
[0.54913425]
[0.5309666]
[0.5416446]
[0.47046044]
[0.46243796]
[0.5213916]
[0.55967456]
[0.5364837]
[0.45869327]
[0.544725]
[0.54800385]
[0.53282946]
[0.533525]
[0.5154342]
[0.5373686]
[0.5147137]
[0.5264629]
[0.4585443]
[0.5360094]
[0.54895425]
[0.509621]
[0.54980576]
[0.5111254]
[0.46982986]
[0.5322362]
[0.52696604]
[0.50173223]
[0.512376]
[0.54420656]
[0.5477479]
[0.5389071]
[0.55655617]
[0.53865325]
[0.5057713]
[0.5319137]
[0.55246097]
[0.4969438]
[0.5362439]
[0.5315254]
[0.5530879]
[0.5505956]
[0.4817715]
[0.50335133]
[0.5318468]
[0.5360679]
[0.5279023]
[0.533601]
[0.53552264]
[0.5396153]
[0.5444781]
[0.4420939]
[0.52880335]
[0.5246203]
[0.48458767]
[0.54558605]
[0.5452423]
[0.54125184]
[0.50092196]
[0.5655371]
[0.5358261]
[0.5365022]

[0.5393214]
[0.53423834]
[0.55860084]
[0.46929014]
[0.53569835]
[0.53160584]
[0.5320348]
[0.5549029]
[0.55459577]
[0.6221671]
[0.46210232]
[0.46254215]
[0.5360337]
[0.53546184]
[0.49096423]
[0.5393052]
[0.5446482]
[0.52389395]
[0.5456146]
[0.53932893]
[0.53123635]
[0.53583646]
[0.5032936]
[0.53236806]
[0.4616655]
[0.5469325]
[0.5349975]
[0.53826725]
[0.5444336]
[0.5365738]
[0.56088555]
[0.5331257]
[0.5293399]
[0.5330631]
[0.5263646]
[0.54347503]
[0.48328143]
[0.53285766]
[0.54512644]
[0.4992923]
[0.5460508]
[0.5508753]
[0.5354436]
[0.53040344]
[0.54048806]
[0.50400543]
[0.5360903]
[0.5271626]
[0.4379104]
[0.53769106]
[0.5319813]
[0.4984308]
[0.47247744]
[0.5509061]
[0.54680365]
[0.53103465]
[0.48325616]
[0.528962]
[0.45421648]
[0.5310695]
[0.54881626]
[0.4445586]
[0.53194976]
[0.5026919]
[0.49367416]
[0.46296352]
[0.5432304]
[0.4825501]
[0.568318]
[0.5244558]
[0.54892087]
[0.5350496]
[0.5581099]
[0.55860204]
[0.44532534]
[0.53960204]
[0.5543461]
[0.55699015]
[0.548851]
[0.5358071]
[0.5

[0.53944993]
[0.44044337]
[0.5301662]
[0.53187877]
[0.5310089]
[0.5489997]
[0.53073424]
[0.5311789]
[0.53990227]
[0.5435356]
[0.5331615]
[0.46225753]
[0.5272603]
[0.52381766]
[0.531815]
[0.5311732]
[0.5514129]
[0.529511]
[0.5045105]
[0.546618]
[0.5421643]
[0.5542149]
[0.5390053]
[0.54328203]
[0.5241135]
[0.50126165]
[0.53059334]
[0.54324543]
[0.5312159]
[0.54911]
[0.5609221]
[0.5413016]
[0.5563713]
[0.55471754]
[0.55164903]
[0.434009]
[0.5487353]
[0.5009216]
[0.54738975]
[0.53493243]
[0.5435054]
[0.4960809]
[0.5500178]
[0.49950162]
[0.501643]
[0.5383033]
[0.5521393]
[0.55173767]
[0.5362077]
[0.4029483]
[0.53256685]
[0.49957585]
[0.53847057]
[0.50788397]
[0.53037095]
[0.55145]
[0.5358175]
[0.50598323]
[0.39762664]
[0.5318524]
[0.52706707]
[0.5512059]
[0.53885406]
[0.5500765]
[0.5299299]
[0.5251332]
[0.5328165]
[0.53603125]
[0.4396346]
[0.52516705]
[0.56102663]
[0.54961646]
[0.53699195]
[0.5095148]
[0.5150114]
[0.542599]
[0.53199023]
[0.53947383]
[0.49883702]
[0.545263]
[0.5358297]
[0.54

[0.5187036]
[0.5319671]
[0.49017066]
[0.53627604]
[0.5354375]
[0.5399504]
[0.5500891]
[0.53874743]
[0.55978197]
[0.4810135]
[0.5318387]
[0.55901825]
[0.53611636]
[0.5480296]
[0.5679922]
[0.5356879]
[0.50692844]
[0.54166853]
[0.5501764]
[0.5402844]
[0.5540035]
[0.5301231]
[0.5522344]
[0.5228721]
[0.5318686]
[0.51842237]
[0.5562281]
[0.42270246]
[0.5482926]
[0.5505467]
[0.53186184]
[0.46829262]
[0.53114265]
[0.55052626]
[0.548956]
[0.5315688]
[0.5327594]
[0.45597285]
[0.5124784]
[0.5047923]
[0.54047674]
[0.5577371]
[0.531849]
[0.5312478]
[0.53634244]
[0.54259044]
[0.5315651]
[0.5471492]
[0.52415866]
[0.5441594]
[0.54255277]
[0.54605645]
[0.53204936]
[0.5435105]
[0.5484801]
[0.5353976]
[0.5560492]
[0.54335165]
[0.54980874]
[0.5402666]
[0.54890996]
[0.53264296]
[0.55240625]
[0.5510961]
[0.5234305]
[0.47943297]
[0.54344314]
[0.46223065]
[0.5484037]
[0.53104204]
[0.51151437]
[0.56074876]
[0.52983433]
[0.5375251]
[0.5327387]
[0.5525846]
[0.54144883]
[0.53340083]
[0.52420574]
[0.55171394]
[0.4

[0.56568074]
[0.5429491]
[0.5568039]
[0.5373133]
[0.55528486]
[0.5362893]
[0.5523513]
[0.54828334]
[0.5075903]
[0.52417487]
[0.55983335]
[0.55212665]
[0.4829806]
[0.5303796]
[0.512707]
[0.531153]
[0.5473935]
[0.55909103]
[0.5101543]
[0.48669055]
[0.5441948]
[0.5411625]
[0.5392061]
[0.5310453]
[0.5316226]
[0.46835348]
[0.53116465]
[0.53616333]
[0.5400854]
[0.5169756]
[0.53866076]
[0.5385624]
[0.53059447]
[0.5361309]
[0.41710106]
[0.52973074]
[0.49640846]
[0.5362362]
[0.53557575]
[0.53578305]
[0.531825]
[0.5074815]
[0.53936404]
[0.48848122]
[0.54337674]
[0.46897683]
[0.5357255]
[0.5455708]
[0.5467924]
[0.5522965]
[0.53620875]
[0.4614107]
[0.5242037]
[0.44625536]
[0.50105065]
[0.5391907]
[0.5245492]
[0.46859977]
[0.54241997]
[0.5583902]
[0.5319072]
[0.56439763]
[0.45274106]
[0.5310405]
[0.54905486]
[0.5528686]
[0.53045905]
[0.5314905]
[0.5303023]
[0.5495278]
[0.4898201]
[0.5568854]
[0.54633737]
[0.52983886]
[0.5046597]
[0.5307382]
[0.5175738]
[0.5244864]
[0.54172397]
[0.5300502]
[0.550076

[0.5355172]
[0.53112996]
[0.5319772]
[0.469221]
[0.5507022]
[0.5367862]
[0.42743292]
[0.46243846]
[0.52432555]
[0.54068875]
[0.5355742]
[0.5440992]
[0.5466563]
[0.54134387]
[0.55001485]
[0.53557295]
[0.5396933]
[0.43183675]
[0.53187495]
[0.53233004]
[0.5514165]
[0.5358088]
[0.4945411]
[0.54231703]
[0.53848857]
[0.53688616]
[0.5424027]
[0.55128187]
[0.53075165]
[0.53584284]
[0.514959]
[0.547396]
[0.5319929]
[0.4982402]
[0.5537355]
[0.55715]
[0.5267517]
[0.48707545]
[0.50569254]
[0.5355874]
[0.5354639]
[0.52634776]
[0.54717034]
[0.52789456]
[0.5327651]
[0.5392294]
[0.5387068]
[0.5351588]
[0.50312597]
[0.5236326]
[0.5297398]
[0.5310548]
[0.54659486]
[0.5364667]
[0.5419493]
[0.5310476]
[0.48583186]
[0.40806586]
[0.49610242]
[0.531203]
[0.53980887]
[0.523978]
[0.5267004]
[0.531849]
[0.5420139]
[0.5226873]
[0.4691155]
[0.5348899]
[0.5239967]
[0.53569096]
[0.5520415]
[0.5482216]
[0.5311943]
[0.5245813]
[0.48077443]
[0.5319813]
[0.5530172]
[0.4870296]
[0.43372977]
[0.5033955]
[0.5362456]
[0.53

[0.47399193]
[0.5391453]
[0.52987605]
[0.53437406]
[0.53614044]
[0.48097357]
[0.52419984]
[0.5329915]
[0.52955884]
[0.48393944]
[0.5319368]
[0.5488124]
[0.5289716]
[0.5419125]
[0.5454933]
[0.39991197]
[0.47367394]
[0.53761077]
[0.53108484]
[0.5316451]
[0.5240035]
[0.53802794]
[0.52401656]
[0.5358615]
[0.5302398]
[0.54351234]
[0.5057867]
[0.53580487]
[0.5310417]
[0.53568584]
[0.5469606]
[0.5237506]
[0.5093426]
[0.54893374]
[0.53584594]
[0.5439016]
[0.5253299]
[0.547595]
[0.43809357]
[0.5511697]
[0.5560059]
[0.4700148]
[0.5318787]
[0.5644928]
[0.547813]
[0.53249604]
[0.5457145]
[0.55942994]
[0.5362677]
[0.47762814]
[0.5431952]
[0.5386173]
[0.5524471]
[0.5310861]
[0.5222298]
[0.568241]
[0.41351482]
[0.5414786]
[0.5501136]
[0.545956]
[0.54701596]
[0.56582665]
[0.53554296]
[0.54494476]
[0.43759146]
[0.4991624]
[0.5342049]
[0.54758745]
[0.53197044]
[0.5361491]
[0.55209315]
[0.47874707]
[0.55471474]
[0.5260352]
[0.5430189]
[0.54868996]
[0.5147479]
[0.5364951]
[0.4375223]
[0.48138538]
[0.53284

KeyboardInterrupt: 

In [55]:
aal=[]
for aa in range(len(b)):
    print(b[aa])
    if b[aa]==0:
        
        aal.append(aa)

KeyError: 0

In [147]:

patho='C://Users//fanyu//Desktop//dpdk//syn'

path=patho+'//'+'syn27pcap_Flow.csv'
#path27=patho+'//'+'syn27pcap_Flow.csv'

osscan=pd.read_csv(path, encoding='ISO-8859-1')
unkown=osscan.drop(osscan.columns[[0,1,2,3,5,6]],axis=1,inplace=False)

unkown_x=unkown.iloc[:,:77]
unkown_y=unkown.iloc[:,77]
#def process():              

#target_xtrain,target_xtest,target_ytrain,target_ytest=cross_validation.train_test_split(target_x,target_y,test_size=0.01)
unkown_xtrain,unkown_ytrain=unkown_x,unkown_y
#target_xtest,target_ytest=target27_x,target27_y
#target_xtrain=target_xtrain.fillna(method='backfill')
    
#target_xtrain=target_xtest.fillna(method='backfill')

xtrain2=pd.DataFrame(unkown_xtrain,dtype=np.float)
c=xtrain2.drop(columns='Flow Bytes/s', axis= 1)
b=c.drop(columns='Flow Packets/s', axis= 1)
xtrain3=preprocessing.StandardScaler().fit_transform(b)
    
#xtest2=pd.DataFrame(unkown_xtest,dtype=np.float)
#m=xtest2.drop(columns='Flow Bytes/s', axis= 1)
#n=m.drop(columns='Flow Packets/s', axis= 1)
#xtest3=preprocessing.StandardScaler().fit_transform(n)



unkown_x_train = xtrain3.reshape((xtrain3.shape[0],xtrain3.shape[1],1))
#unkown_x_test =xtest3.reshape((xtest3.shape[0],xtest3.shape[1],1))

#X_train = np.reshape(trainX, (trainX.shape[0],trainX.shape[1],1))
#X_test = np.reshape(testT, (testT.shape[0],testT.shape[1],1))




In [148]:
unkown_res_t=discriminator1.predict(target_feature.predict(unkown_x_train))

In [150]:
discriminator1.predict(target_feature.predict(target_x_train))

array([[3.5890291e-11],
       [1.7701798e-06],
       [1.2271839e-10],
       ...,
       [8.6070859e-06],
       [9.3339195e-06],
       [9.6822732e-06]], dtype=float32)

In [152]:
y_pre=unkown_res_t.tolist()
target_be=[21,37,62,68,78,83,100,114,145,163,176,180,195,209,227,241,
245,260,273,307,312,314,329,344,371,391,485,491,495]
y_true=[]
for t in range(497):
    if t in target_be:
        y_true.append(0)
    else:
        y_true.append(1)
#画PR曲线
import matplotlib.pyplot as plt
import numpy as np
from sklearn import metrics
#y_true=source_y_test.tolist()
#y_pre=res_s.tolist()

#precision, recall, _thresholds = metrics.precision_recall_curve(y_test, y_score)
precision, recall, _thresholds = metrics.precision_recall_curve(y_true, y_pre)
pr_auc = metrics.auc(recall, precision)
lw = 2

from sklearn.metrics import roc_curve, auc
fpr, tpr, threshold = roc_curve(y_true, y_pre)  ###计算真正率和假正率
roc_auc = auc(fpr, tpr) 
pr_auc,roc_auc

(0.8944370494853617, 0.5053050397877984)

In [156]:
threshold

array([1.00002038e+00, 2.03836626e-05, 1.77579295e-05, 1.76988578e-05,
       1.76680478e-05, 1.67260005e-05, 1.67222843e-05, 1.66355003e-05,
       1.02240165e-05, 1.02236172e-05, 9.52490427e-06, 8.30850877e-06,
       7.81869130e-06, 7.81790095e-06, 6.07543734e-06, 1.67845217e-11,
       7.88503513e-14])

In [172]:
y_pred=[]
for i in y_pre:
    if i[0]>6.07543734e-06:
        y_pred.append(1)
    else:
        y_pred.append(0)
len(y_pred)

497

In [173]:
import sklearn
from sklearn.metrics import roc_auc_score
#y_pred=[y>6.07543734e-06 for y in y_pre]
C=confusion_matrix(y_true, y_pred)
C

acc=(C[0,0]+C[1,1])/C.sum()
acc

#sklearn.metrics.f1_score(y_true, y_pred),roc_auc_score(y_true, y_pred)

0.9678068410462777

In [176]:
tpr=C[1,1]/(C[1,0]+C[1,1])
fpr=C[1,0]/(C[1,0]+C[1,1])
import sklearn
from sklearn.metrics import roc_auc_score
sklearn.metrics.f1_score(y_true, y_pred),roc_auc_score(y_true, y_pred)
#C,tpr,fpr

(0.983157894736842, 0.7403109342764516)

In [137]:
res_t

array([[0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 2.5310020e-38,
        0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 3.4267720e-34,
        0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 4.3974928e-35,
        0.0000000e+00],
       ...,
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 2.9798310e-13,
        0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 3.3706967e-13,
        0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 3.4060219e-13,
        0.0000000e+00]], dtype=float32)

In [138]:
res_t=target_cnn.predict(target_x_train)
res_t
ind=0
ll=[]
for r in res_t:
    xxx=r.tolist()
    #if(xxx.index(max(xxx))==3):
    if xxx[3]<3.3706967e-35:
        print(ind)
        ll.append(ind)
    ind+=1
len(ll)

0
3
6
9
13
16
17
20
24
28
30
31
33
34
38
42
45
47
48
50
52
56
58
59
62
65
66
70
73
75
77
80
82
84
85
87
88
41985
49214
56721
58637


41

In [139]:
target_be=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,81,82,83,84,85,86,87,88,89,594,11331,14596,15255,31756,46563,55502,56721]
y_true=[]
for t in range(len(target_x_train)):
    if t in target_be:
        y_true.append(0)
    else:
        y_true.append(1)
y_pred=[]
for t in range(len(target_x_train)):
    if t in ll:
        y_pred.append(0)
    else:
        y_pred.append(1)



In [140]:
import seaborn as sns
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
C=confusion_matrix(y_true, y_pred)
C

acc=(C[0,0]+C[1,1])/C.sum()
acc

0.9990254450213946

In [143]:
tpr=C[1,1]/(C[1,0]+C[1,1])
fpr=C[1,0]/(C[1,0]+C[1,1])

tpr,fpr


(0.9999390002134992, 6.099978650074725e-05)

In [145]:
import sklearn
sklearn.metrics.f1_score(y_true, y_pred)

0.9995122099935978

In [146]:
import sklearn
sklearn.metrics.f1_score(y_true, y_pred)
from sklearn.metrics import roc_auc_score
roc_auc_score(y_true, y_pred)

0.6906911495912857

In [142]:
C


array([[   37,    60],
       [    4, 65570]], dtype=int64)

In [320]:
target_cnn.save(r'D:\a\model\success-benign+ddos+portscan-benign+syndos\target_cnn.h5')
source_cnn.save(r'D:\a\model\success-benign+ddos+portscan-benign+syndos\source_cnn.h5')
target_feature.save(r'D:\a\model\success-benign+ddos+portscan-benign+syndos\target_feature.h5')
source_feature.save(r'D:\a\model\success-benign+ddos+portscan-benign+syndos\source_feature.h5')
discriminator1.save(r'D:\a\model\success-benign+ddos+portscan-benign+syndos\discriminator1.h5')
discriminator2.save(r'D:\a\model\success-benign+ddos+portscan-benign+syndos\discriminator2.h5')

In [316]:
res_s_t=source_cnn.predict(target_x_test)
res_s_t
ind=0
for r in res_s_t:
    xxx=r.tolist()
    if(xxx.index(max(xxx))==):
        print(ind)
    ind+=1

62
273
307
485


In [103]:
res_s=source_cnn.predict(target_x_test)

In [264]:
res_t=target_cnn.predict(target_x_test)
ind=0
for r in res_t:
    xxx=r.tolist()
    if(xxx.index(max(xxx))==1):
        print(ind)
    ind+=1

In [42]:
#target_cnn.layers[-1].set_weights(source_cnn.layers[-1].get_weights())
print("Saving model to disk \n")
target_cnn_path = "D://a//model//target_cnn_categorial.h5"
target_cnn.save(target_cnn_path)

print("Saving model to disk \n")
source_cnn_path = "D://a//model//source_cnn_categorial.h5"
source_cnn.save(source_cnn_path)

Saving model to disk 

Saving model to disk 



In [198]:
target_cnn.get_weights()[-1]

array([-0.04182427], dtype=float32)

In [201]:
res_t

array([[0.38996637],
       [0.36400247],
       [0.38994375],
       [0.3992089 ],
       [0.33416152],
       [0.38426185],
       [0.38831568],
       [0.32183406],
       [0.40059608],
       [0.39406437],
       [0.40057647],
       [0.38585934],
       [0.3277136 ],
       [0.3857701 ],
       [0.38450566],
       [0.38980013],
       [0.37085775],
       [0.30246583],
       [0.4008458 ],
       [0.29234672],
       [0.35809603],
       [0.2953891 ],
       [0.36857572],
       [0.3860774 ],
       [0.38453057],
       [0.38975203],
       [0.3860094 ],
       [0.38461146],
       [0.3611336 ],
       [0.4005669 ],
       [0.3889285 ],
       [0.2848991 ],
       [0.35494754],
       [0.38944182],
       [0.38438445],
       [0.3939648 ],
       [0.3801079 ],
       [0.12252929],
       [0.3501325 ],
       [0.31928852],
       [0.38428804],
       [0.38910604],
       [0.3399465 ],
       [0.39852718],
       [0.3674044 ],
       [0.38977093],
       [0.38601008],
       [0.385

In [205]:
la=[21,37,62,68,78,83,100,114,145,163,176,180,195,209,227,241,245,260,273,307,312,314,329,344,371,391,485,491,495]
target_test_label=[]
for i in range(len(target_x_test)):
    if i in la:
        target_test_label.append(0)
    else:
        target_test_label.append(1)
#target_test_label

In [202]:
res_t=target_cnn.predict(target_x_test)
ind=0
for r in res_t:
    
    if r<0.3:
        print(ind)
    ind+=1

19
21
31
37
67
68
74
78
100
114
142
145
146
152
163
176
180
193
195
198
209
227
241
244
245
247
260
312
329
330
337
344
371
381
391
430
439
461
480
481
485
491
495


In [208]:
res_s_t=source_cnn.predict(target_x_test)

In [206]:
#画PR曲线
import matplotlib.pyplot as plt
import numpy as np
from sklearn import metrics
#y_true=source_y_test.tolist()
#y_pre=res_s.tolist()
y_true=target_test_label
y_pre=res_t.tolist()
#precision, recall, _thresholds = metrics.precision_recall_curve(y_test, y_score)
precision, recall, _thresholds = metrics.precision_recall_curve(y_true, y_pre)
pr_auc = metrics.auc(recall, precision)
lw = 2

from sklearn.metrics import roc_curve, auc
fpr, tpr, threshold = roc_curve(y_true, y_pre)  ###计算真正率和假正率
roc_auc = auc(fpr, tpr) 
pr_auc,roc_auc

(0.98266587782906, 0.9103300913645741)

In [226]:
#画PR曲线
import matplotlib.pyplot as plt
import numpy as np
from sklearn import metrics
#y_true=source_y_test.tolist()
#y_pre=res_s.tolist()
y_true=target_test_label
y_pre=res_t.tolist()
#precision, recall, _thresholds = metrics.precision_recall_curve(y_test, y_score)
precision, recall, _thresholds = metrics.precision_recall_curve(y_true, y_pre)
pr_auc = metrics.auc(recall, precision)
lw = 2

from sklearn.metrics import roc_curve, auc
fpr, tpr, threshold = roc_curve(y_true, y_pre)  ###计算真正率和假正率
roc_auc = auc(fpr, tpr) 
pr_auc,roc_auc

(0.98266587782906, 0.9103300913645741)

In [227]:
##指标acc，f1
y_pred =[int(y[0]>=0.5) for y in y_pre]
acc=metrics.accuracy_score(y_true, y_pred)

f1=metrics.f1_score(y_true, y_pred)
f1,acc

D:\Anaconda3.6\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


(0.0, 0.05835010060362173)

In [105]:
res_t=source_cnn.predict(target_x_test)

In [76]:
res_s

array([[1.0000000e+00],
       [7.7060491e-01],
       [9.7491052e-12],
       ...,
       [1.0000000e+00],
       [4.3934178e-06],
       [3.0839162e-10]], dtype=float32)

In [14]:
from sklearn.decomposition import PCA
from sklearn import manifold, datasets
from matplotlib import pyplot as plt
#初始化一个可以将高维度特征向量压缩至2个维度的PCA
#estimator=PCA(n_components=2)
#x_pca=estimator.fit_transform(x_digits)

tsne = manifold.TSNE(n_components=2, init='pca', random_state=501)
source_x_test2 =source_x_test.reshape((source_x_test.shape[0],source_x_test.shape[1]))
target_x_test2 =target_x_test.reshape((target_x_test.shape[0],target_x_test.shape[1]))
source_tsne = tsne.fit_transform(source_x_test2)
target_tsne = tsne.fit_transform(target_x_test2)

def plot_pca_scatter(x_pca,label):
    fig=plt.figure(figsize=(10,10))
    colors=['black','red']
    for i in range(len(colors)):
        px=x_pca[:,0][label==i]
        py=x_pca[:,1][label==i]
        plt.scatter(px,py,c=colors[i],marker='x')
    plt.legend(np.arange(0,10).astype(str))
    plt.xlabel('First PC')
    plt.ylabel('Second PC')
    plt.show()
#plot_pca_scatter(source_tsne,source_y_test)
#plot_pca_scatter(target_pca,ytrain2)

In [18]:
st_tsne=np.vstack([source_tsne,target_tsne])

st_y=np.vstack([source_y_test,target_test_label])
st_tsne.shape,st_y.shape
#plot_pca_scatter(st_tsne,st_y)
#plot_pca_scatter(target_pca,ytrain2)

NameError: name 'target_test_label' is not defined